name: "Setup"
description: "Sets up Python environment and installs dependencies"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.torch/iopath_cache
          ~/.paddleocr/whl
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.py', 'install.py', '**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Run install script
      shell: bash
      run: ./install.sh
