name: Setup Python
on:
  workflow_call:

jobs:
  setup-python:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.torch/iopath_cache
            ~/.paddleocr/whl
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py', 'install.py', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
