name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/setup-python.yml

  install:
    needs: setup
    uses: ./.github/workflows/install-deps.yml

  smoketest:
    needs: install
    name: Smoke Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Run smoke test"
        run: lp-labelstudio process-newspaper --redo src/lp_labelstudio/web_server/test_images/

      - name: "Verify results"
        run: |
          cat src/lp_labelstudio/web_server/test_images/page_01_annotations.json|jq -C
          cat src/lp_labelstudio/web_server/test_images/page_02_annotations.json|jq -C

  unit-tests:
    needs: install
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest
